spring.application.name=demo
spring.datasource.url=jdbc:postgresql://localhost:5433/demo
spring.datasource.username=postgres
spring.datasource.password=aviation_password
spring.datasource.driver-class-name=org.postgresql.Driver
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true